### PR TITLE
verify if already exists any smb.conf before creating one

### PR DESCRIPTION
**Pull request by mzramna**
sugestion to reutilize already existing smb.conf files to import them and avoid to uselessly recreate them

### CODE REVIEW

**Review by elswork — COMMENTED** [review]
Thanks for your Pull Request @mzramna 
I would prefer to not leave open this possibility for simplicity, in a container environment for most users is hard to know the state of files inside a container and it could bring troubles. in a container environment.

**Comment by elswork** [comment]
Thanks for your Pull Request @mzramna
I would prefer to not leave open this possibility for simplicity, in a container environment for most users is hard to know the state of files inside a container and it could bring troubles. in a container environment.

**Comment by mzramna** [comment]
i've made this because i'm having some trouble when restart the container,exactaly because it always recreates this file and it make me recreate the conainer every time i restart the pc i'm running the container,just by doing this it solves the problem

**Comment by elswork** [comment]
You are right, thanks for your explanation.

**Comment by kongkrit** [comment]
Could you please elaborate more why recreating `smb.conf` file is a problem?
I'm trying to understand it.
1. if you issue a `docker start mysamba` after the server was stopped, then there's no issue. am i correct?
2. would this code add everything else besides the head of the config file to `smb.conf` when it was run for the second time?

thank you for your clarifications.

**Comment by mzramna** [comment]
`if you issue a docker start mysamba after the server was stopped, then there's no issue. am i correct?`
no,i dont know exactaly how,but it enters into al infinite loop of error,like it try to recreate the smb.conf and reboot ,than it fives another error,but to be fair,i save this file into a mount drive,not edit this,just to debug easily if i change the container(never happend,but anyway)
`would this code add everything else besides the head of the config file to smb.conf when it was run for the second time?`
this code JUST verify if the file already exists and does not recreate it,is also an minimal disk write utilization optimization,in raspberry pi sd card any disk optimization is an good optimization since it has an limit of readwrites smaller than other media drives
this edit does almost nothing,i know this,but is an small I/O disk write redution,i also understant that if you want to edit the container mounts you will delete or replace itself,could have an doublecheck if the file is needed to be recreated,but i didnt do this,but could try to do later

**Comment by kongkrit** [comment]
Hi mzramna,

Ok. I'm not knowledgeable enough to know why. But, I don't see any harm if its' there. It already got pulled in to the main repo, and I have no problem with that--it reduces write wear as you said.

The reason I asked was because your PR skipped creating the `[global]` section, but if there were some arguments passed to `entrypoint.sh`, new shares could be added to `smb.conf`.

Thank you.

**Pull request merged**
